# Generated by Django 3.1.2 on 2020-11-02 00:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='activations_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='buyer',
            name='activations_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 0, 22, 4, 864834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
