# Generated by Django 3.1.2 on 2020-11-02 20:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20201102_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='activations_key',
            new_name='activation_key',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='activations_key_expires',
        ),
        migrations.AddField(
            model_name='buyer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 20, 38, 39, 620617, tzinfo=utc)),
        ),
    ]
