# Generated by Django 3.1.2 on 2020-11-05 00:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20201105_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 0, 15, 42, 262257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.DateField(default=18, verbose_name='Ваша дата рождения'),
        ),
    ]
