# Generated by Django 3.1.2 on 2020-11-05 01:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20201105_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 1, 26, 28, 211252, tzinfo=utc)),
        ),
    ]
