# Generated by Django 3.1.2 on 2020-11-05 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20201105_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 22, 42, 30, 343704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=128, verbose_name='Теги'),
        ),
    ]
